name: iis-test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  powershell-script:
    runs-on: windows-2022
    steps:
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Test the PowerShell module instructions from README.md
        shell: powershell
        run: |
          $module_url = "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/OpenTelemetry.DotNet.Auto.psm1"
          $dl_path = Join-Path $env:temp "OpenTelemetry.DotNet.Auto.psm1"
          $log_path = "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\*"
          Invoke-WebRequest -Uri $module_url -OutFile $dl_path
          Import-Module $dl_path
          Install-OpenTelemetryCore
          $install_dir = Get-OpenTelemetryInstallDirectory
          Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
          dotnet help
          If (-not (Test-Path $log_path)) { throw "Log file does not exist. Instrumentation test failed." }
          Remove-Item $log_path
          Unregister-OpenTelemetryForCurrentSession
          dotnet help
          If (Test-Path $log_path) { throw "Log file exists. Instrumentation unregister failed." }
          Uninstall-OpenTelemetryCore
          If (Test-Path $install_dir) { throw "Core files exist. Core uninstall failed." }

  powershell-script-with-iis:
    runs-on: windows-2022
    steps:
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Test the PowerShell module instructions from README.md
        shell: powershell
        run: |
          Add-WindowsFeature Web-Server
          Start-Service W3SVC
          $module_url = "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/OpenTelemetry.DotNet.Auto.psm1"
          $dl_path = Join-Path $env:temp "OpenTelemetry.DotNet.Auto.psm1"
          $log_path = "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\*"
          Invoke-WebRequest -Uri $module_url -OutFile $dl_path
          Import-Module $dl_path
          Install-OpenTelemetryCore
          $install_dir = Get-OpenTelemetryInstallDirectory
          Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
          dotnet help
          If (-not (Test-Path $log_path)) { throw "Log file does not exist. Instrumentation test failed." }
          Remove-Item $log_path
          Unregister-OpenTelemetryForCurrentSession
          dotnet help
          If (Test-Path $log_path) { throw "Log file exists. Instrumentation unregister failed." }
          Uninstall-OpenTelemetryCore
          If (Test-Path $install_dir) { throw "Core files exist. Core uninstall failed." }
